# Generated by Django 4.2.24 on 2025-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_result_tonase_result_tonnage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboard',
            },
        ),
    ]
